### ISSUE TITLE
What Hadoop/Spark configuration should be set to use s3committer?

### ISSUE THREAD

**Issue by danielhaviv** [rdblue/s3committer#9]
Hi,
The README does not state which configurations should be set to use s3committer.

I have tried using the following properties and nothing seems to work:
val conf = new SparkConf().set("spark.hadoop.mapred.output.committer.class","com.netflix.bdp.s3.S3DirectoryOutputCommitter ")
conf.set("spark.sql.sources.outputCommitterClass","com.netflix.bdp.s3.S3DirectoryOutputCommitter")
conf.set("spark.hadoop.mapreduce.use.directfileoutputcommitter","false”)
spark.sql(“SET spark.hadoop.mapred.output.committer.class= com.netflix.bdp.s3.S3DirectoryOutputCommitter”)

Please advise.

Thank you.
Daniel

**Comment by praneetsharma** [comment]
Hi @danielhaviv 

If you look at the implementation of getOutputCommitter method in FileOutputFormat.java, you will see that we are only creating an object on FileOutputCommitter. The property you mentioned would have worked for old MapReduce API.

To use S3DirectoryOutputCommitter (or any other custom committer), you will have to create a new class which extends FileOutputFormat. In that class, only implement getOutputCommitter method to create an object of your custom committer. Now, to use this custom output format class, Set the following in the runtimeConfig of SparkSession: `mapreduce.job.outputformat.class` to the custom class.

**Comment by chuwy** [comment]
Still struggling to enable it on EMR Spark 2.2.0 with following:

```scala
class S3OutputFormat[K, V] extends org.apache.hadoop.mapreduce.lib.output.FileOutputFormat[K, V] {
  override def getOutputCommitter(context: TaskAttemptContext): OutputCommitter =
    new S3DirectoryOutputCommitter(FileOutputFormat.getOutputPath(context), context)

  override def getRecordWriter(job: TaskAttemptContext): RecordWriter[K, V] = ???
}

val config = new SparkConf().set("mapreduce.job.outputformat.class", "me.chuwy.sparkjob.S3OutputFormat")
val sc = new SparkContext(config)
```

Is there anything super-obvious that I'm missing in config? Does it work with RDDs?

**Comment by danielhaviv** [comment]
Hi,
EMR now comes with it built in
https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-spark-s3-optimized-committer.html

BR.
Daniel

**Comment by chuwy** [comment]
Thanks @danielhaviv. But unfortunately as documentation states, S3-optimized committer works only with Parquet, whereas I need to write newline-delimited JSON.
